name: Update and Convert Publications

permissions:
  contents: write

on:
  # Trigger when publications.bib is updated
  push:
    branches: ['main']
    paths: ['publications.bib']

  # Trigger on the 1st day of the month
  schedule:
    - cron: "0 0 1 * *"

  # Allow manual trigger
  workflow_dispatch:

jobs:
  update_and_convert:
    runs-on: ubuntu-latest
    steps:
      # Checkout the repository
      - name: Checkout the repo
        uses: actions/checkout@v4

      # Set up Python for both the BibTeX update and conversion
      - name: Set up Python 3.12
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      # Install dependencies for both update and conversion
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install scholarly bibtexparser academic==0.10.0

      # Step to update the publications.bib file
      - name: Run publications update
        run: python update_publications.py  # Your script to fetch and update publications.bib

      # Convert the updated BibTeX file to Markdown-based webpages
      - name: Run Academic (BibTeX To Markdown Converter)
        # Check `.bib` file exists for case when action runs on `.bib` deletion
        if: ${{ hashFiles('publications.bib') != '' }}
        run: academic import publications.bib content/publication/ --compact

      # Commit and push the updated publications.bib and Markdown files
      - name: Commit changes
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: 'content: update and convert publications'
          file_pattern: |
            publications.bib
            content/publication/**
